trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  jdkVersion: '1.11'

steps:
- checkout: self

- task: Cache@2
  inputs:
    key: 'gradle | "$(Agent.OS)" | **/*.gradle*'
    restoreKeys: |
      gradle | "$(Agent.OS)"
    path: ~/.gradle

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    options: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '$(jdkVersion)'
    jdkArchitectureOption: 'x64'

- publish: build/libs
  artifact: drop
